 # Generated by Django 3.1 on 2020-08-11 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200811_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='series',
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'series')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'series')},
        ),
    ]
