# Generated by Django 3.1 on 2020-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200811_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
